_app_root:
    path: /
    controller: App\Controller\AppController

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix:
        en: '/en'
        fr: '/fr'